version: "3"
services:
  automation:
    build:
      context: ../
      dockerfile: docker/Dockerfile.gui
    container_name: automation
    networks:
    - default
    volumes:
    - ../reports:/reports
    env_file: 
    - ../.env
    environment:
    - PYTHONPATH=/
